---
linters-settings:
  govet:
    check-shadowing: false
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 200
  maligned:
    suggest-new: true
  dupl:
    threshold: 250
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    rules:
      - name: atomic
      - name: blank-imports
      - name: confusing-naming
      - name: get-return
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: struct-tag
      - name: time-naming
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
        arguments: [
          "fmt.Printf",
          "fmt.Println",
          "fmt.Fprintf",
        ]
      - name: unreachable-code
      - name: unused-parameter
      - name: var-declaration
      - name: var-naming

run:
  timeout: 5m
  # skip directories: vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  # Fail if the error was met.
  issues-exit-code: 1

linters:
  enable:
#    - deadcode
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nilerr
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unused
#    - varcheck
    - whitespace


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false