name: CI

on: [push]

# env:
#  SKIP_LDAP: true
#  SKIP_MAIL: true
#  SKIP_ORACLE: true
#  SKIP_COMMIT: true
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor
      - name: Test
        env:
          # github copies the files with api, not as clone, check fails
          # https://github.com/actions/checkout/issues/335
          SKIP_COMMIT: true
          # github cannot handle custom resolvers, so skip dns tests
          SKIP_DNS: true
        run: go test -v ./...  -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v9
        with:
          version: "v2.7.2"
          args: --timeout=10m
          skip-cache: true